const { vi } = require('vitest');

module.exports = {
    getAllUsers: vi.fn(),
    createUser: vi.fn(),
    getUserById: vi.fn(),
    updateUserById: vi.fn(),
    getAllPosts: vi.fn(),
    getPostById: vi.fn(),
    createPost: vi.fn(),
    updatePost: vi.fn(),
    deletePostById: vi.fn(),
    getBlogById: vi.fn(),
    deleteBlogById: vi.fn(),
    getAllTopics: vi.fn(),
    createTopic: vi.fn(),
    updateTopic: vi.fn(),
    toggleBanUserById: vi.fn(),
    getCoaches: vi.fn(),
    getCoachDetailsById: vi.fn(),
    getAllUserSubscriptions: vi.fn(),
    createUserSubscription: vi.fn(),
    updateUserSubscription: vi.fn(),
    deleteUserSubscription: vi.fn(),
};